timezone = "Europe/London"

[discord]
guild_id = 1234567890

[ferry]
api_url = "https://example.com/api/v1/"
api_key = "abc"
channel_id = 1234567890
banned_word = "train"
emoji_reacts = "🚂😠🚇"

[pub]
weekday = 3  # Thursday
hour = 20
channel_id = 1234567890
description = "Casual chat and food. All welcome."

[[pub.pubs]]
name = "The Fleming Arms"
emoji = "🦾"
menu_url = "https://www.hungryhorse.co.uk/pubs/hampshire/fleming-arms/menu/"
map_url = "https://g.page/theflemingarms"

[[pub.pubs]]
name = "Brewhouse and Kitchen"
emoji = "🍺"
menu_url = "https://www.brewhouseandkitchen.com/venue/southampton/"
map_url = "https://goo.gl/maps/F1JZ8WrzU1qx8bFp7"

[[pub.pubs]]
name = "Trago Lounge"
emoji = "🛋️"
menu_url = "https://thelounges.co.uk/trago/#menu"
map_url = "https://goo.gl/maps/ZzCziQ76zxV7x7uJ9"

[[pub.pubs]]
name = "The Cowherds"
emoji = "🐄"
menu_url = "https://www.vintageinn.co.uk/restaurants/south-east/thecowherdssouthampton/restaurantsfood#/"
map_url = "https://goo.gl/maps/mXFbSKJ2ZEzoTzat8"

[[pub.pubs]]
name = "The Crown Inn"
emoji = "👑"
map_url = "https://goo.gl/maps/k6ZDtKoxchDNK94WA"
